/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/waitlist/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Waitlist Signup */
        post: operations["waitlist_signup_api_v1_auth_waitlist_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_api_v1_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Account */
        post: operations["activate_account_api_v1_auth_activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["refresh_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change Password */
        put: operations["change_password_api_v1_auth_change_password_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User */
        get: operations["get_current_user_api_v1_users_me_get"];
        /** Update Profile */
        put: operations["update_profile_api_v1_users_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Notification Prefs
         * @description Get notification preferences for the current user.
         */
        get: operations["get_notification_prefs_api_v1_settings_notifications_get"];
        /**
         * Update Notification Prefs
         * @description Update notification preferences (partial update).
         */
        put: operations["update_notification_prefs_api_v1_settings_notifications_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/privacy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Privacy Settings
         * @description Get privacy and data settings for the current user.
         */
        get: operations["get_privacy_settings_api_v1_settings_privacy_get"];
        /**
         * Update Privacy Settings
         * @description Update privacy and data settings (partial update).
         */
        put: operations["update_privacy_settings_api_v1_settings_privacy_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/account/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate Account
         * @description Temporarily deactivate the current user's account.
         */
        post: operations["deactivate_account_api_v1_settings_account_deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description Permanently delete the current user's account and associated data.
         */
        delete: operations["delete_account_api_v1_settings_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get assessment questions
         * @description Return the structured question bank for a given assessment category.
         *     Defaults to `tech_freelancer`.
         */
        get: operations["get_assessment_questions_api_v1_risk_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available assessment categories
         * @description Return metadata for all available risk assessment categories.
         */
        get: operations["list_categories_api_v1_risk_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/assessment/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a risk assessment
         * @description Run the full scoring + AI pipeline for the given freelancer category
         *     and persist the result. Currently supports: `tech_freelancer`.
         *
         *     The `category` path parameter must match `data.occupation`.
         */
        post: operations["submit_assessment_api_v1_risk_assessment__category__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/assessment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get latest risk assessment
         * @description Retrieve the most recent risk assessment for the authenticated user.
         */
        get: operations["get_latest_assessment_api_v1_risk_assessment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get assessment history
         * @description Return a chronological list of all past assessments for the authenticated user.
         */
        get: operations["get_assessment_history_api_v1_risk_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get product recommendations
         * @description Return insurance product recommendations derived from the user's
         *     latest risk assessment.
         */
        get: operations["get_recommendations_api_v1_risk_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kyc/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Identity
         * @description Submit NIN or BVN for identity verification via Smile ID.
         */
        post: operations["verify_identity_api_v1_kyc_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kyc/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Kyc Status
         * @description Get the current KYC verification status for the authenticated user.
         */
        get: operations["get_kyc_status_api_v1_kyc_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kyc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Smile Id Callback
         * @description Webhook endpoint for asynchronous Smile ID verification results.
         */
        post: operations["smile_id_callback_api_v1_kyc_callback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_v1_marketplace_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recommendations */
        get: operations["get_recommendations_api_v1_marketplace_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_v1_marketplace_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Policies */
        get: operations["list_policies_api_v1_policies_get"];
        put?: never;
        /** Create Policy */
        post: operations["create_policy_api_v1_policies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policy Summary */
        get: operations["policy_summary_api_v1_policies_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Policy */
        get: operations["get_policy_api_v1_policies__policy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mock Pay */
        post: operations["mock_pay_api_v1_policies__policy_id__pay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{policy_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policy Report */
        get: operations["policy_report_api_v1_policies__policy_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Overview */
        get: operations["get_dashboard_overview_api_v1_dashboard_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Claims */
        get: operations["list_claims"];
        put?: never;
        /** Submit Claim */
        post: operations["submit_claim"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{claim_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Claim */
        get: operations["get_claim"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/initialize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initialize Payment */
        post: operations["initialize_payment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/{payment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Payment */
        get: operations["get_payment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Payment History */
        get: operations["get_payment_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivateAccountRequest */
        ActivateAccountRequest: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /**
         * ApplicantProfile
         * @description Personal info echoed back in assessment responses.
         */
        ApplicantProfile: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Age */
            age: number;
            /** Gender */
            gender: string;
            /** Marital Status */
            marital_status: string;
            /** State */
            state: string;
            /** City */
            city: string;
        };
        /**
         * AssessmentResponse
         * @description Full response returned after submitting a risk assessment.
         */
        AssessmentResponse: {
            applicant: components["schemas"]["ApplicantProfile"];
            /** Category */
            category: string;
            pillar_scores: components["schemas"]["PillarScores"];
            /** Overall Score */
            overall_score: number;
            /** Risk Profile */
            risk_profile: string;
            /** Recommendations */
            recommendations: string[];
            /** Recommended Categories */
            recommended_categories?: string[];
            /** Ai Insights */
            ai_insights: string;
        };
        /**
         * AssessmentSummary
         * @description Lightweight summary for history listings.
         */
        AssessmentSummary: {
            /** Id */
            id: string;
            /** Category */
            category: string;
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Age */
            age?: number | null;
            /** Overall Score */
            overall_score: number;
            /** Risk Profile */
            risk_profile: string;
            /** Created At */
            created_at: string;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            old_password: string;
            new_password: string;
        };
        /** DeleteAccountRequest */
        DeleteAccountRequest: {
            /** Password */
            password: string;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KYCStatusResponse */
        KYCStatusResponse: {
            /** Status */
            status: string | null;
            /** Document Type */
            document_type: string | null;
            /** Verified At */
            verified_at: string | null;
            /** Rejection Reason */
            rejection_reason: string | null;
        };
        /** KYCVerifyRequest */
        KYCVerifyRequest: {
            /**
             * Document Type
             * @constant
             */
            document_type: "NIN";
            /** Document Number */
            document_number: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Date Of Birth */
            date_of_birth: string;
        };
        /** KYCVerifyResponse */
        KYCVerifyResponse: {
            /** Status */
            status: string;
            /** Message */
            message: string;
            /** Smile Job Id */
            smile_job_id?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            email: string;
            password: string;
        };
        /** NotificationPrefsResponse */
        NotificationPrefsResponse: {
            /** Risk Score Updates */
            risk_score_updates: boolean;
            /** Premium Renewals */
            premium_renewals: boolean;
            /** New Plan Recommendations */
            new_plan_recommendations: boolean;
            /** Payment Confirmations */
            payment_confirmations: boolean;
            /** Product Updates */
            product_updates: boolean;
        };
        /** PrivacySettingsResponse */
        PrivacySettingsResponse: {
            /** Share Anonymised Data */
            share_anonymised_data: boolean;
            /** Personalise Recommendations */
            personalise_recommendations: boolean;
            /** Share Data With Partners */
            share_data_with_partners: boolean;
        };
        /** PillarScores */
        PillarScores: {
            /** Income */
            income: number;
            /** Client */
            client: number;
            /** Safety */
            safety: number;
            /** Equipment */
            equipment: number;
            /** Health */
            health: number;
        };
        /** RefreshTokenRequest */
        RefreshTokenRequest: {
            refresh_token: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            first_name: string;
            last_name?: string | null;
        };
        /** ResendActivationRequest */
        ResendActivationRequest: {
            /** Format: email */
            email: string;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            token: string;
            new_password: string;
        };
        /** SmileIDCallbackPayload */
        SmileIDCallbackPayload: {
            /** Signature */
            signature: string;
            /** Timestamp */
            timestamp: string;
            /** Smilejobid */
            SmileJobID: string;
            /** Resultcode */
            ResultCode: string;
            /** Resulttext */
            ResultText: string;
            /** Actions */
            Actions: {
                [key: string]: unknown;
            };
            /** Partnerparams */
            PartnerParams: {
                [key: string]: unknown;
            };
        };
        /**
         * TechAssessmentInput
         * @description Full survey payload submitted by a tech freelancer.
         */
        TechAssessmentInput: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Date Of Birth */
            date_of_birth: string;
            /** Gender */
            gender: string;
            /** State */
            state: string;
            /** City */
            city: string;
            /** Occupation */
            occupation: string;
            /** Marital Status */
            marital_status: string;
            /** Age */
            age?: number | null;
            /** Job Type */
            job_type: string;
            /** Freelance Duration */
            freelance_duration: string;
            /** Client Geography */
            client_geography: string;
            /** Work Mode */
            work_mode: string;
            /** Weekly Hours */
            weekly_hours: string;
            /** Monthly Income Band */
            monthly_income_band: string;
            /** Income Stability */
            income_stability: string;
            /** Income Sources */
            income_sources: string;
            /** Biggest Client Loss */
            biggest_client_loss: string;
            /** Past Risks */
            past_risks: string[];
            /** Top Worries */
            top_worries: string[];
            /** Equipment Dependency */
            equipment_dependency: string;
            /** Pre Existing Conditions */
            pre_existing_conditions: boolean;
            /** Chronic Illness */
            chronic_illness: boolean;
            /** Smoker */
            smoker: boolean;
            /** Health Rating */
            health_rating: number;
            /** Travel Frequency */
            travel_frequency: string;
            /** Survival 3 Months */
            survival_3_months: string;
            /** Savings Duration */
            savings_duration: string;
            /** Insurance Types */
            insurance_types: string[];
            /** Insurance Claims */
            insurance_claims: string;
            /** Protection Priority */
            protection_priority: string;
        };
        /** DashboardOverviewResponse */
        DashboardOverviewResponse: {
            /** @default 0 */
            premiums_bought: number;
            monthly_income_band?: string | null;
            safety_buffer?: string | null;
            /** @default 0 */
            recommended_plans_count: number;
            income_stability?: components["schemas"]["IncomeStabilityPattern"] | null;
            /** @default false */
            has_assessment: boolean;
        };
        /** IncomeStabilityPattern */
        IncomeStabilityPattern: {
            score: number;
            classification: string;
            graph_points: number[];
        };
        /** PolicyCreate */
        PolicyCreate: {
            product_id: string;
        };
        /** PolicyListResponse */
        PolicyListResponse: {
            items: components["schemas"]["PolicyOut"][];
        };
        /** PolicyOut */
        PolicyOut: {
            id: string;
            status: string;
            display_status: string;
            coverage_amount: string;
            premium_amount: string;
            premium_currency: string;
            renewal_frequency: string;
            start_date?: string | null;
            end_date?: string | null;
            purchased_at?: string | null;
            external_policy_id?: string | null;
            /** Format: date-time */
            created_at: string;
            product: components["schemas"]["PolicyProductSummary"];
        };
        /** PolicyProductSummary */
        PolicyProductSummary: {
            id: string;
            name: string;
            category: string;
            provider_name: string;
            provider_slug: string;
        };
        /** PolicySummary */
        PolicySummary: {
            total_coverage: string;
            active_count: number;
            due_soon_count: number;
        };
        /** ProductListResponse */
        ProductListResponse: {
            items: components["schemas"]["ProductOut"][];
            total: number;
            limit: number;
            offset: number;
        };
        /** ProductOut */
        ProductOut: {
            id: string;
            name: string;
            category: string;
            description: string;
            premium_amount: string;
            premium_currency: string;
            coverage_amount: string;
            renewal_frequency: string;
            risk_level?: string | null;
            is_active: boolean;
            provider: components["schemas"]["ProviderRef"];
        };
        /** ProviderRef */
        ProviderRef: {
            id: string;
            slug: string;
            name: string;
            logo_url?: string | null;
        };
        /** RecommendedProductsResponse */
        RecommendedProductsResponse: {
            recommended_categories: string[];
            items: components["schemas"]["ProductOut"][];
        };
        /**
         * RecommendationsResponse
         * @description Standalone recommendations response (without full assessment payload).
         */
        RecommendationsResponse: {
            /** Recommendations */
            recommendations: string[];
            /** Overall Score */
            overall_score?: number | null;
            /** Risk Profile */
            risk_profile?: string | null;
        };
        /** TokenResponse */
        TokenResponse: {
            access_token: string;
            refresh_token: string;
            /** @default bearer */
            token_type: string;
            /**
             * Kyc Verified
             * @default false
             */
            kyc_verified: boolean;
            /**
             * Risk Assessed
             * @default false
             */
            risk_assessed: boolean;
        };
        /** UpdateNotificationPrefsRequest */
        UpdateNotificationPrefsRequest: {
            /** Risk Score Updates */
            risk_score_updates?: boolean | null;
            /** Premium Renewals */
            premium_renewals?: boolean | null;
            /** New Plan Recommendations */
            new_plan_recommendations?: boolean | null;
            /** Payment Confirmations */
            payment_confirmations?: boolean | null;
            /** Product Updates */
            product_updates?: boolean | null;
        };
        /** UpdatePrivacySettingsRequest */
        UpdatePrivacySettingsRequest: {
            /** Share Anonymised Data */
            share_anonymised_data?: boolean | null;
            /** Personalise Recommendations */
            personalise_recommendations?: boolean | null;
            /** Share Data With Partners */
            share_data_with_partners?: boolean | null;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            first_name?: string | null;
            last_name?: string | null;
            phone_number?: string | null;
            date_of_birth?: string | null;
            gender?: string | null;
            address_line_1?: string | null;
            address_line_2?: string | null;
            city?: string | null;
            state?: string | null;
            country?: string | null;
            postal_code?: string | null;
            occupation?: string | null;
            gig_platform?: string | null;
            average_monthly_income?: number | string | null;
            years_of_experience?: number | null;
            profile_picture_url?: string | null;
        };
        /** UserProfileResponse */
        UserProfileResponse: {
            date_of_birth?: string | null;
            gender?: string | null;
            address_line_1?: string | null;
            address_line_2?: string | null;
            city?: string | null;
            state?: string | null;
            country?: string | null;
            postal_code?: string | null;
            occupation?: string | null;
            gig_platform?: string | null;
            average_monthly_income?: string | null;
            years_of_experience?: number | null;
            profile_picture_url?: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /** Format: uuid */
            id: string;
            email: string;
            phone_number?: string | null;
            first_name: string;
            last_name?: string | null;
            status: string;
            role: string;
            email_verified: boolean;
            last_login_at?: string | null;
            created_at?: string | null;
        };
        /** UserWithProfileResponse */
        UserWithProfileResponse: {
            user: components["schemas"]["UserResponse"];
            profile?: components["schemas"]["UserProfileResponse"] | null;
            /**
             * Kyc Verified
             * @default false
             */
            kyc_verified: boolean;
            /**
             * Risk Assessed
             * @default false
             */
            risk_assessed: boolean;
        };
        /** ValidationError */
        ValidationError: {
            loc: (string | number)[];
            msg: string;
            type: string;
            input?: unknown;
            ctx?: Record<string, never>;
        };
        /** VerifyEmailRequest */
        VerifyEmailRequest: {
            token: string;
        };
        /** WaitlistSignupRequest */
        WaitlistSignupRequest: {
            /** Format: email */
            email: string;
            first_name: string;
            last_name?: string | null;
        };
        /** WaitlistSignupResponse */
        WaitlistSignupResponse: {
            message: string;
            user_id: string;
            access_token: string;
            /** @default bearer */
            token_type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    waitlist_signup_api_v1_auth_waitlist_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaitlistSignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitlistSignupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_api_v1_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_account_api_v1_auth_activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_password_api_v1_auth_change_password_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserWithProfileResponse"];
                };
            };
        };
    };
    update_profile_api_v1_users_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserWithProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notification_prefs_api_v1_settings_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPrefsResponse"];
                };
            };
        };
    };
    update_notification_prefs_api_v1_settings_notifications_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotificationPrefsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPrefsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_privacy_settings_api_v1_settings_privacy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivacySettingsResponse"];
                };
            };
        };
    };
    update_privacy_settings_api_v1_settings_privacy_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePrivacySettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivacySettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_account_api_v1_settings_account_deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_account_api_v1_settings_account_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assessment_questions_api_v1_risk_questions_get: {
        parameters: {
            query?: {
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_v1_risk_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    submit_assessment_api_v1_risk_assessment__category__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TechAssessmentInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_assessment_api_v1_risk_assessment_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentResponse"];
                };
            };
        };
    };
    get_assessment_history_api_v1_risk_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentSummary"][];
                };
            };
        };
    };
    get_recommendations_api_v1_risk_recommendations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsResponse"];
                };
            };
        };
    };
    verify_identity_api_v1_kyc_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KYCVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KYCVerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kyc_status_api_v1_kyc_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KYCStatusResponse"];
                };
            };
        };
    };
    smile_id_callback_api_v1_kyc_callback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmileIDCallbackPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_api_v1_marketplace_products_get: {
        parameters: {
            query?: {
                category?: string[] | null;
                provider_slug?: string[] | null;
                risk_level?: string[] | null;
                q?: string | null;
                min_premium?: number | string | null;
                max_premium?: number | string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendations_api_v1_marketplace_recommendations_get: {
        parameters: {
            query?: {
                per_category?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendedProductsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_v1_marketplace_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_policies_api_v1_policies_get: {
        parameters: {
            query?: {
                status_filter?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyListResponse"];
                };
            };
        };
    };
    create_policy_api_v1_policies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
        };
    };
    policy_summary_api_v1_policies_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicySummary"];
                };
            };
        };
    };
    get_policy_api_v1_policies__policy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
        };
    };
    mock_pay_api_v1_policies__policy_id__pay_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
        };
    };
    policy_report_api_v1_policies__policy_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_dashboard_overview_api_v1_dashboard_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOverviewResponse"];
                };
            };
        };
    };
    list_claims: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submit_claim: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_claim: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    initialize_payment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_payment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_payment_history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
